import type { GeocodingSearchResult } from '@maptiler/client';

/**
 * CERN address data from MapTiler
 * Request: https://api.maptiler.com/geocoding/6.055619932005584,46.233004881941895.json?types=address%2Cpostal_code%2Cmunicipality%2Ccounty%2Cregion&language=en
 */
export const CERN = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      properties: {
        ref: 'osm:w77073776',
        country_code: 'ch',
        kind: 'place',
        place_type_name: ['address'],
      },
      geometry: {
        type: 'Point',
        coordinates: [6.055555026158572, 46.232983890386336],
      },
      bbox: [
        6.055555026158625, 46.232983890386336, 6.055555026158625,
        46.232983890386336,
      ],
      center: [6.055555026158572, 46.232983890386336],
      place_name: 'CERN SITE DE MEYRIN 33, 1217 Meyrin, Switzerland',
      place_type: ['address'],
      relevance: 1,
      id: 'address.18111041',
      text: 'CERN SITE DE MEYRIN',
      place_type_name: ['address'],
      context: [
        {
          ref: 'osm:n4361127392',
          id: 'postal_code.1754478',
          text: '1217',
          country_code: 'ch',
          text_en: '1217',
        },
        {
          ref: 'osm:w77073776',
          id: 'place.4311615',
          text: 'CERN SITE DE MEYRIN',
          country_code: 'ch',
          kind: 'place',
          text_en: 'CERN SITE DE MEYRIN',
        },
        {
          ref: 'osm:r1685516',
          id: 'municipality.10294',
          text: 'Meyrin',
          country_code: 'ch',
          wikidata: 'Q68230',
          kind: 'admin_area',
          'osm:place_type': 'town',
          text_en: 'Meyrin',
        },
        {
          ref: 'osm:r1702419',
          id: 'region.223',
          text: 'Geneva',
          country_code: 'ch',
          wikidata: 'Q11917',
          kind: 'admin_area',
          'osm:place_type': 'state',
          language: 'en',
          text_en: 'Geneva',
          language_en: 'en',
        },
        {
          ref: 'osm:r27005',
          id: 'major_landform.4412126',
          text: 'CERN - Meyrin site',
          country_code: 'ch,fr',
          wikidata: 'Q42944',
          categories: ['industrial'],
          language: 'en',
          'osm:tags': {
            'contact:youtube': 'https://www.youtube.com/user/cerntv',
            'contact:facebook': 'https://www.facebook.com/cern',
            amenity: 'research_institute',
            office: 'research',
            'contact:email': 'service-desk@cern.ch',
            type: 'multipolygon',
            operator: 'CERN',
            'contact:instagram': 'https://www.instagram.com/cern',
            landuse: 'industrial',
            wikipedia: 'en:CERN',
            'contact:website': 'https://home.cern',
            'contact:twitter': 'https://x.com/CERN',
            start_date: '1954-09-29',
            image:
              'https://upload.wikimedia.org/wikipedia/commons/9/90/CERN-aerial_1.jpg',
            man_made: 'particle_accelerator',
            'contact:tiktok': 'https://www.tiktok.com/@cern_ontiktok',
            substance: 'proton',
            'contact:linkedin': 'https://www.linkedin.com/company/cern',
            'contact:phone': '+41 0 22 76 77777',
          },
          text_en: 'CERN - Meyrin site',
          language_en: 'en',
        },
        {
          ref: 'osm:r51701',
          id: 'country.196',
          text: 'Switzerland',
          country_code: 'ch',
          wikidata: 'Q39',
          kind: 'admin_area',
          'osm:place_type': 'country',
          language: 'en',
          text_en: 'Switzerland',
          language_en: 'en',
        },
        {
          ref: 'osm:n25871341',
          id: 'continental_marine.1',
          text: 'Europe',
          wikidata: 'Q46',
          categories: ['continent'],
          language: 'en',
          'osm:tags': {
            population: '739165030',
            place: 'continent',
            wikipedia: 'eo:Eŭropo',
            sqkm: '10180000',
          },
          text_en: 'Europe',
          language_en: 'en',
        },
      ],
      address: '33',
      text_en: 'CERN SITE DE MEYRIN',
      place_name_en: 'CERN SITE DE MEYRIN 33, 1217 Meyrin, Switzerland',
    },
    {
      type: 'Feature',
      properties: {
        ref: 'osm:n4361127392',
        country_code: 'ch',
        place_type_name: ['postal code'],
      },
      geometry: {
        type: 'Point',
        coordinates: [6.074570182217258, 46.22952851637285],
      },
      bbox: [
        6.048625409603119, 46.21710918264044, 6.097391992807388,
        46.24207456533054,
      ],
      center: [6.074570182217258, 46.22952851637285],
      place_name: '1217, Switzerland',
      place_type: ['postal_code'],
      relevance: 1,
      id: 'postal_code.1754478',
      text: '1217',
      place_type_name: ['postal code'],
      context: [
        {
          ref: 'osm:w77073776',
          id: 'place.4311615',
          text: 'CERN SITE DE MEYRIN',
          country_code: 'ch',
          kind: 'place',
          text_en: 'CERN SITE DE MEYRIN',
        },
        {
          ref: 'osm:r1685516',
          id: 'municipality.10294',
          text: 'Meyrin',
          country_code: 'ch',
          wikidata: 'Q68230',
          kind: 'admin_area',
          'osm:place_type': 'town',
          text_en: 'Meyrin',
        },
        {
          ref: 'osm:r1702419',
          id: 'region.223',
          text: 'Geneva',
          country_code: 'ch',
          wikidata: 'Q11917',
          kind: 'admin_area',
          'osm:place_type': 'state',
          language: 'en',
          text_en: 'Geneva',
          language_en: 'en',
        },
        {
          ref: 'osm:r27005',
          id: 'major_landform.4412126',
          text: 'CERN - Meyrin site',
          country_code: 'ch,fr',
          wikidata: 'Q42944',
          categories: ['industrial'],
          language: 'en',
          'osm:tags': {
            'contact:youtube': 'https://www.youtube.com/user/cerntv',
            'contact:facebook': 'https://www.facebook.com/cern',
            amenity: 'research_institute',
            office: 'research',
            'contact:email': 'service-desk@cern.ch',
            type: 'multipolygon',
            operator: 'CERN',
            'contact:instagram': 'https://www.instagram.com/cern',
            landuse: 'industrial',
            wikipedia: 'en:CERN',
            'contact:website': 'https://home.cern',
            'contact:twitter': 'https://x.com/CERN',
            start_date: '1954-09-29',
            image:
              'https://upload.wikimedia.org/wikipedia/commons/9/90/CERN-aerial_1.jpg',
            man_made: 'particle_accelerator',
            'contact:tiktok': 'https://www.tiktok.com/@cern_ontiktok',
            substance: 'proton',
            'contact:linkedin': 'https://www.linkedin.com/company/cern',
            'contact:phone': '+41 0 22 76 77777',
          },
          text_en: 'CERN - Meyrin site',
          language_en: 'en',
        },
        {
          ref: 'osm:r51701',
          id: 'country.196',
          text: 'Switzerland',
          country_code: 'ch',
          wikidata: 'Q39',
          kind: 'admin_area',
          'osm:place_type': 'country',
          language: 'en',
          text_en: 'Switzerland',
          language_en: 'en',
        },
        {
          ref: 'osm:n25871341',
          id: 'continental_marine.1',
          text: 'Europe',
          wikidata: 'Q46',
          categories: ['continent'],
          language: 'en',
          'osm:tags': {
            population: '739165030',
            place: 'continent',
            wikipedia: 'eo:Eŭropo',
            sqkm: '10180000',
          },
          text_en: 'Europe',
          language_en: 'en',
        },
      ],
      text_en: '1217',
      place_name_en: '1217, CERN SITE DE MEYRIN, Meyrin, Geneva, Switzerland',
    },
    {
      type: 'Feature',
      properties: {
        ref: 'osm:r1685516',
        country_code: 'ch',
        wikidata: 'Q68230',
        kind: 'admin_area',
        'osm:place_type': 'town',
        place_type_name: ['municipality'],
      },
      geometry: {
        type: 'Point',
        coordinates: [6.079100480447323, 46.23222956290981],
      },
      bbox: [
        6.0461121797561646, 46.2171739069227, 6.1118993908166885,
        46.24712586728471,
      ],
      center: [6.079100480447323, 46.23222956290981],
      place_name: 'Meyrin, Geneva, Switzerland',
      place_type: ['municipality'],
      relevance: 1,
      id: 'municipality.10294',
      text: 'Meyrin',
      place_type_name: ['municipality'],
      context: [
        {
          ref: 'osm:r1702419',
          id: 'region.223',
          text: 'Geneva',
          country_code: 'ch',
          wikidata: 'Q11917',
          kind: 'admin_area',
          'osm:place_type': 'state',
          language: 'en',
          text_en: 'Geneva',
          language_en: 'en',
        },
        {
          ref: 'osm:r27005',
          id: 'major_landform.4412126',
          text: 'CERN - Meyrin site',
          country_code: 'ch,fr',
          wikidata: 'Q42944',
          categories: ['industrial'],
          language: 'en',
          'osm:tags': {
            'contact:youtube': 'https://www.youtube.com/user/cerntv',
            'contact:facebook': 'https://www.facebook.com/cern',
            amenity: 'research_institute',
            office: 'research',
            'contact:email': 'service-desk@cern.ch',
            type: 'multipolygon',
            operator: 'CERN',
            'contact:instagram': 'https://www.instagram.com/cern',
            landuse: 'industrial',
            wikipedia: 'en:CERN',
            'contact:website': 'https://home.cern',
            'contact:twitter': 'https://x.com/CERN',
            start_date: '1954-09-29',
            image:
              'https://upload.wikimedia.org/wikipedia/commons/9/90/CERN-aerial_1.jpg',
            man_made: 'particle_accelerator',
            'contact:tiktok': 'https://www.tiktok.com/@cern_ontiktok',
            substance: 'proton',
            'contact:linkedin': 'https://www.linkedin.com/company/cern',
            'contact:phone': '+41 0 22 76 77777',
          },
          text_en: 'CERN - Meyrin site',
          language_en: 'en',
        },
        {
          ref: 'osm:r51701',
          id: 'country.196',
          text: 'Switzerland',
          country_code: 'ch',
          wikidata: 'Q39',
          kind: 'admin_area',
          'osm:place_type': 'country',
          language: 'en',
          text_en: 'Switzerland',
          language_en: 'en',
        },
        {
          ref: 'osm:n25871341',
          id: 'continental_marine.1',
          text: 'Europe',
          wikidata: 'Q46',
          categories: ['continent'],
          language: 'en',
          'osm:tags': {
            population: '739165030',
            place: 'continent',
            wikipedia: 'eo:Eŭropo',
            sqkm: '10180000',
          },
          text_en: 'Europe',
          language_en: 'en',
        },
      ],
      text_en: 'Meyrin',
      place_name_en: 'Meyrin, Geneva, Switzerland',
    },
    {
      type: 'Feature',
      properties: {
        ref: 'osm:r1702419',
        country_code: 'ch',
        wikidata: 'Q11917',
        kind: 'admin_area',
        'osm:place_type': 'state',
        place_type_name: ['canton'],
      },
      geometry: {
        type: 'Point',
        coordinates: [6.143920607864857, 46.22565096854365],
      },
      bbox: [
        5.955831706523895, 46.12855022541987, 6.310287639498711,
        46.364573048887216,
      ],
      center: [6.143920607864857, 46.22565096854365],
      place_name: 'Geneva, Switzerland',
      place_type: ['region'],
      relevance: 1,
      id: 'region.223',
      text: 'Geneva',
      place_type_name: ['canton'],
      context: [
        {
          ref: 'osm:r27005',
          id: 'major_landform.4412126',
          text: 'CERN - Meyrin site',
          country_code: 'ch,fr',
          wikidata: 'Q42944',
          categories: ['industrial'],
          language: 'en',
          'osm:tags': {
            'contact:youtube': 'https://www.youtube.com/user/cerntv',
            'contact:facebook': 'https://www.facebook.com/cern',
            amenity: 'research_institute',
            office: 'research',
            'contact:email': 'service-desk@cern.ch',
            type: 'multipolygon',
            operator: 'CERN',
            'contact:instagram': 'https://www.instagram.com/cern',
            landuse: 'industrial',
            wikipedia: 'en:CERN',
            'contact:website': 'https://home.cern',
            'contact:twitter': 'https://x.com/CERN',
            start_date: '1954-09-29',
            image:
              'https://upload.wikimedia.org/wikipedia/commons/9/90/CERN-aerial_1.jpg',
            man_made: 'particle_accelerator',
            'contact:tiktok': 'https://www.tiktok.com/@cern_ontiktok',
            substance: 'proton',
            'contact:linkedin': 'https://www.linkedin.com/company/cern',
            'contact:phone': '+41 0 22 76 77777',
          },
          text_en: 'CERN - Meyrin site',
          language_en: 'en',
        },
        {
          ref: 'osm:r51701',
          id: 'country.196',
          text: 'Switzerland',
          country_code: 'ch',
          wikidata: 'Q39',
          kind: 'admin_area',
          'osm:place_type': 'country',
          language: 'en',
          text_en: 'Switzerland',
          language_en: 'en',
        },
        {
          ref: 'osm:n25871341',
          id: 'continental_marine.1',
          text: 'Europe',
          wikidata: 'Q46',
          categories: ['continent'],
          language: 'en',
          'osm:tags': {
            population: '739165030',
            place: 'continent',
            wikipedia: 'eo:Eŭropo',
            sqkm: '10180000',
          },
          text_en: 'Europe',
          language_en: 'en',
        },
      ],
      language: 'en',
      text_en: 'Geneva',
      language_en: 'en',
      place_name_en: 'Geneva, Switzerland',
    },
  ],
  query: [6.055619932005584, 46.233004881941895],
  attribution:
    '<a href="https://www.maptiler.com/copyright/" target="_blank">&copy; MapTiler</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>',
} as unknown as GeocodingSearchResult;

/**
 * NASA address data from MapTiler
 * Request: https://api.maptiler.com/geocoding/-80.67996942379177,28.52512053465631.json?types=address%2Cpostal_code%2Cmunicipality%2Ccounty%2Cregion&language=en
 */
export const NASA = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      properties: {
        ref: 'osm:w1093015263',
        country_code: 'us',
        kind: 'street',
        place_type_name: ['address'],
      },
      geometry: {
        type: 'Point',
        coordinates: [-80.67490658995888, 28.525111579130627],
      },
      bbox: [
        -80.67490658995888, 28.525111579130627, -80.67490658995888,
        28.525111579130627,
      ],
      center: [-80.67490658995888, 28.525111579130627],
      place_name:
        '3535 NASA Parkway West, Brevard, Florida 32953, United States',
      place_type: ['address'],
      relevance: 1,
      id: 'address.23742203',
      text: 'NASA Parkway West',
      place_type_name: ['address'],
      context: [
        {
          ref: 'oa:../oa-us/us/fl/statewide-state/2ccf222f412d1566',
          id: 'postal_code.3357098',
          text: '32953',
          country_code: 'us',
          text_en: '32953',
        },
        {
          ref: 'osm:n7714474007',
          id: 'place.4825752',
          text: 'Merritt Island',
          country_code: 'us',
          wikidata: 'Q991010',
          kind: 'place',
          'osm:place_type': 'town',
          text_en: 'Merritt Island',
        },
        {
          ref: 'osm:r389024',
          id: 'county.18225',
          text: 'Brevard',
          country_code: 'us',
          wikidata: 'Q488517',
          kind: 'admin_area',
          'osm:place_type': 'county',
          text_en: 'Brevard',
        },
        {
          ref: 'osm:r162050',
          id: 'region.3096',
          text: 'Florida',
          country_code: 'us',
          wikidata: 'Q812',
          kind: 'admin_area',
          'osm:place_type': 'state',
          language: 'en',
          text_en: 'Florida',
          language_en: 'en',
        },
        {
          ref: 'osm:r148838',
          id: 'country.1222',
          text: 'United States',
          country_code: 'us',
          wikidata: 'Q30',
          kind: 'admin_area',
          'osm:place_type': 'country',
          language: 'en',
          text_en: 'United States',
          language_en: 'en',
        },
        {
          ref: 'osm:n36966063',
          id: 'continental_marine.4',
          text: 'North America',
          wikidata: 'Q49',
          categories: ['continent'],
          language: 'en',
          'osm:tags': {
            population: '528720588',
            place: 'continent',
            wikipedia: 'en:North America',
            sqkm: '24709000',
          },
          text_en: 'North America',
          language_en: 'en',
        },
      ],
      address: '3535',
      text_en: 'NASA Parkway West',
      place_name_en:
        '3535 NASA Parkway West, Brevard, Florida 32953, United States',
    },
    {
      type: 'Feature',
      properties: {
        ref: 'oa:../oa-us/us/fl/statewide-state/2ccf222f412d1566',
        country_code: 'us',
        place_type_name: ['postal code'],
      },
      geometry: {
        type: 'Point',
        coordinates: [-80.70294245435826, 28.421291855597286],
      },
      bbox: [
        -80.72481863786734, 28.350703, -80.64322779999999, 28.576205599999984,
      ],
      center: [-80.70294245435826, 28.421291855597286],
      place_name: '32953, Florida, United States',
      place_type: ['postal_code'],
      relevance: 1,
      id: 'postal_code.3357098',
      text: '32953',
      place_type_name: ['postal code'],
      context: [
        {
          ref: 'osm:n7714474007',
          id: 'place.4825752',
          text: 'Merritt Island',
          country_code: 'us',
          wikidata: 'Q991010',
          kind: 'place',
          'osm:place_type': 'town',
          text_en: 'Merritt Island',
        },
        {
          ref: 'osm:r389024',
          id: 'county.18225',
          text: 'Brevard',
          country_code: 'us',
          wikidata: 'Q488517',
          kind: 'admin_area',
          'osm:place_type': 'county',
          text_en: 'Brevard',
        },
        {
          ref: 'osm:r162050',
          id: 'region.3096',
          text: 'Florida',
          country_code: 'us',
          wikidata: 'Q812',
          kind: 'admin_area',
          'osm:place_type': 'state',
          language: 'en',
          text_en: 'Florida',
          language_en: 'en',
        },
        {
          ref: 'osm:r148838',
          id: 'country.1222',
          text: 'United States',
          country_code: 'us',
          wikidata: 'Q30',
          kind: 'admin_area',
          'osm:place_type': 'country',
          language: 'en',
          text_en: 'United States',
          language_en: 'en',
        },
        {
          ref: 'osm:n36966063',
          id: 'continental_marine.4',
          text: 'North America',
          wikidata: 'Q49',
          categories: ['continent'],
          language: 'en',
          'osm:tags': {
            population: '528720588',
            place: 'continent',
            wikipedia: 'en:North America',
            sqkm: '24709000',
          },
          text_en: 'North America',
          language_en: 'en',
        },
      ],
      text_en: '32953',
      place_name_en: '32953, Merritt Island, Brevard, Florida, United States',
    },
    {
      type: 'Feature',
      properties: {
        ref: 'osm:r389024',
        country_code: 'us',
        wikidata: 'Q488517',
        kind: 'admin_area',
        'osm:place_type': 'county',
        place_type_name: ['county'],
      },
      geometry: {
        type: 'Point',
        coordinates: [-80.79971864819527, 28.210020399639244],
      },
      bbox: [
        -80.98801407963036, 27.82205814730768, -80.38506925106049,
        28.791396134951064,
      ],
      center: [-80.79971864819527, 28.210020399639244],
      place_name: 'Brevard, Florida, United States',
      place_type: ['county'],
      relevance: 1,
      id: 'county.18225',
      text: 'Brevard',
      place_type_name: ['county'],
      context: [
        {
          ref: 'osm:r162050',
          id: 'region.3096',
          text: 'Florida',
          country_code: 'us',
          wikidata: 'Q812',
          kind: 'admin_area',
          'osm:place_type': 'state',
          language: 'en',
          text_en: 'Florida',
          language_en: 'en',
        },
        {
          ref: 'osm:r148838',
          id: 'country.1222',
          text: 'United States',
          country_code: 'us',
          wikidata: 'Q30',
          kind: 'admin_area',
          'osm:place_type': 'country',
          language: 'en',
          text_en: 'United States',
          language_en: 'en',
        },
        {
          ref: 'osm:n36966063',
          id: 'continental_marine.4',
          text: 'North America',
          wikidata: 'Q49',
          categories: ['continent'],
          language: 'en',
          'osm:tags': {
            population: '528720588',
            place: 'continent',
            wikipedia: 'en:North America',
            sqkm: '24709000',
          },
          text_en: 'North America',
          language_en: 'en',
        },
      ],
      text_en: 'Brevard',
      place_name_en: 'Brevard, Florida, United States',
    },
    {
      type: 'Feature',
      properties: {
        ref: 'osm:r162050',
        country_code: 'us',
        wikidata: 'Q812',
        kind: 'admin_area',
        'osm:place_type': 'state',
        place_type_name: ['state'],
      },
      geometry: {
        type: 'Point',
        coordinates: [-81.4639838039875, 27.756766773533865],
      },
      bbox: [
        -87.63489615172148, 24.39630829832564, -79.97430603951216,
        31.000762236966608,
      ],
      center: [-81.4639838039875, 27.756766773533865],
      place_name: 'Florida, United States',
      place_type: ['region'],
      relevance: 1,
      id: 'region.3096',
      text: 'Florida',
      place_type_name: ['state'],
      context: [
        {
          ref: 'osm:r148838',
          id: 'country.1222',
          text: 'United States',
          country_code: 'us',
          wikidata: 'Q30',
          kind: 'admin_area',
          'osm:place_type': 'country',
          language: 'en',
          text_en: 'United States',
          language_en: 'en',
        },
        {
          ref: 'osm:n36966063',
          id: 'continental_marine.4',
          text: 'North America',
          wikidata: 'Q49',
          categories: ['continent'],
          language: 'en',
          'osm:tags': {
            population: '528720588',
            place: 'continent',
            wikipedia: 'en:North America',
            sqkm: '24709000',
          },
          text_en: 'North America',
          language_en: 'en',
        },
      ],
      language: 'en',
      text_en: 'Florida',
      language_en: 'en',
      place_name_en: 'Florida, United States',
    },
  ],
  query: [-80.67996942379176, 28.52512053465631],
  attribution:
    '<a href="https://www.maptiler.com/copyright/" target="_blank">&copy; MapTiler</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>',
} as unknown as GeocodingSearchResult;

/**
 * Stonehenge address data from MapTiler
 * Request: https://api.maptiler.com/geocoding/-1.826179271164449,51.17884907055111.json?key=fCzNlOAToHmoHPwtIObx&types=address%2Cpostal_code%2Cmunicipality%2Ccounty%2Cregion&language=en
 */
export const STONEHENGE = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      properties: {
        ref: 'osm:w152183996',
        country_code: 'gb',
        kind: 'street',
        place_type_name: ['address'],
      },
      geometry: {
        type: 'Point',
        coordinates: [-1.8273811354133613, 51.18327357185926],
      },
      bbox: [
        -1.8326706066727638, 51.17583621130897, -1.8235688656568527,
        51.191244327613596,
      ],
      center: [-1.8273811354133613, 51.18327357185926],
      place_name: 'Byway 12, Amesbury, Wiltshire SP4 7DE, United Kingdom',
      place_type: ['address'],
      relevance: 1,
      id: 'address.3780158',
      text: 'Byway 12',
      place_type_name: ['address'],
      context: [
        {
          ref: 'osm:w287145736',
          id: 'postal_code.142079',
          text: 'SP4 7DE',
          country_code: 'gb',
          text_en: 'SP4 7DE',
        },
        {
          ref: 'osm:r3404415',
          id: 'municipality.73871',
          text: 'Amesbury',
          country_code: 'gb',
          wikidata: 'Q470299',
          kind: 'admin_area',
          'osm:place_type': 'town',
          text_en: 'Amesbury',
        },
        {
          ref: 'osm:r57533',
          id: 'county.2616',
          text: 'Wiltshire',
          country_code: 'gb',
          wikidata: 'Q21694746',
          kind: 'admin_area',
          'osm:place_type': 'county',
          language: 'en',
          text_en: 'Wiltshire',
          language_en: 'en',
        },
        {
          ref: 'osm:r58447',
          id: 'region.1220',
          text: 'England',
          country_code: 'gb',
          wikidata: 'Q21',
          kind: 'admin_area',
          'osm:place_type': 'state',
          language: 'en',
          text_en: 'England',
          language_en: 'en',
        },
        {
          ref: 'osm:r9345787',
          id: 'major_landform.4552872',
          text: 'Stonehenge Avebury and Associated Sites WHS',
          country_code: 'gb',
          categories: [
            'protected area',
            'intercontinental treaties or conventions nature protected area',
          ],
          'osm:tags': {
            boundary: 'protected_area',
            protect_class: '98',
            protection_title: 'world_heritage_convention',
            ref: '373',
            website: 'https://whc.unesco.org/en/list/373',
            heritage: '1',
            designation: 'world_heritage_convention',
            type: 'boundary',
          },
          text_en: 'Stonehenge Avebury and Associated Sites WHS',
        },
        {
          ref: 'osm:r62149',
          id: 'country.185',
          text: 'United Kingdom',
          country_code: 'gb',
          wikidata: 'Q145',
          kind: 'admin_area',
          'osm:place_type': 'country',
          language: 'en',
          text_en: 'United Kingdom',
          language_en: 'en',
        },
        {
          ref: 'osm:n25871341',
          id: 'continental_marine.1',
          text: 'Europe',
          wikidata: 'Q46',
          categories: ['continent'],
          language: 'en',
          'osm:tags': {
            population: '739165030',
            place: 'continent',
            wikipedia: 'eo:Eŭropo',
            sqkm: '10180000',
          },
          text_en: 'Europe',
          language_en: 'en',
        },
      ],
      text_en: 'Byway 12',
      place_name_en: 'Byway 12, Amesbury, Wiltshire SP4 7DE, United Kingdom',
    },
    {
      type: 'Feature',
      properties: {
        ref: 'osm:w287145736',
        country_code: 'gb',
        place_type_name: ['postal code'],
      },
      geometry: {
        type: 'Point',
        coordinates: [-1.847649611902625, 51.18297548321659],
      },
      bbox: [
        -1.8594686671316367, 51.17884746470144, -1.8261474848057162,
        51.185753877194706,
      ],
      center: [-1.847649611902625, 51.18297548321659],
      place_name: 'SP4 7DE, United Kingdom',
      place_type: ['postal_code'],
      relevance: 1,
      id: 'postal_code.142079',
      text: 'SP4 7DE',
      place_type_name: ['postal code'],
      context: [
        {
          ref: 'osm:r3404415',
          id: 'municipality.73871',
          text: 'Amesbury',
          country_code: 'gb',
          wikidata: 'Q470299',
          kind: 'admin_area',
          'osm:place_type': 'town',
          text_en: 'Amesbury',
        },
        {
          ref: 'osm:r57533',
          id: 'county.2616',
          text: 'Wiltshire',
          country_code: 'gb',
          wikidata: 'Q21694746',
          kind: 'admin_area',
          'osm:place_type': 'county',
          language: 'en',
          text_en: 'Wiltshire',
          language_en: 'en',
        },
        {
          ref: 'osm:r58447',
          id: 'region.1220',
          text: 'England',
          country_code: 'gb',
          wikidata: 'Q21',
          kind: 'admin_area',
          'osm:place_type': 'state',
          language: 'en',
          text_en: 'England',
          language_en: 'en',
        },
        {
          ref: 'osm:r9345787',
          id: 'major_landform.4552872',
          text: 'Stonehenge Avebury and Associated Sites WHS',
          country_code: 'gb',
          categories: [
            'protected area',
            'intercontinental treaties or conventions nature protected area',
          ],
          'osm:tags': {
            boundary: 'protected_area',
            protect_class: '98',
            protection_title: 'world_heritage_convention',
            ref: '373',
            website: 'https://whc.unesco.org/en/list/373',
            heritage: '1',
            designation: 'world_heritage_convention',
            type: 'boundary',
          },
          text_en: 'Stonehenge Avebury and Associated Sites WHS',
        },
        {
          ref: 'osm:r62149',
          id: 'country.185',
          text: 'United Kingdom',
          country_code: 'gb',
          wikidata: 'Q145',
          kind: 'admin_area',
          'osm:place_type': 'country',
          language: 'en',
          text_en: 'United Kingdom',
          language_en: 'en',
        },
        {
          ref: 'osm:n25871341',
          id: 'continental_marine.1',
          text: 'Europe',
          wikidata: 'Q46',
          categories: ['continent'],
          language: 'en',
          'osm:tags': {
            population: '739165030',
            place: 'continent',
            wikipedia: 'eo:Eŭropo',
            sqkm: '10180000',
          },
          text_en: 'Europe',
          language_en: 'en',
        },
      ],
      text_en: 'SP4 7DE',
      place_name_en: 'SP4 7DE, Amesbury, Wiltshire, England, United Kingdom',
    },
    {
      type: 'Feature',
      properties: {
        ref: 'osm:r3404415',
        country_code: 'gb',
        wikidata: 'Q470299',
        kind: 'admin_area',
        'osm:place_type': 'town',
        place_type_name: ['municipality'],
      },
      geometry: {
        type: 'Point',
        coordinates: [-1.78175188601017, 51.17230037761255],
      },
      bbox: [
        -1.8535586446523666, 51.14945396924139, -1.7117002978920934,
        51.19192491819506,
      ],
      center: [-1.78175188601017, 51.17230037761255],
      place_name: 'Amesbury, Wiltshire, United Kingdom',
      place_type: ['municipality'],
      relevance: 1,
      id: 'municipality.73871',
      text: 'Amesbury',
      place_type_name: ['municipality'],
      context: [
        {
          ref: 'osm:r57533',
          id: 'county.2616',
          text: 'Wiltshire',
          country_code: 'gb',
          wikidata: 'Q21694746',
          kind: 'admin_area',
          'osm:place_type': 'county',
          language: 'en',
          text_en: 'Wiltshire',
          language_en: 'en',
        },
        {
          ref: 'osm:r58447',
          id: 'region.1220',
          text: 'England',
          country_code: 'gb',
          wikidata: 'Q21',
          kind: 'admin_area',
          'osm:place_type': 'state',
          language: 'en',
          text_en: 'England',
          language_en: 'en',
        },
        {
          ref: 'osm:r9345787',
          id: 'major_landform.4552872',
          text: 'Stonehenge Avebury and Associated Sites WHS',
          country_code: 'gb',
          categories: [
            'protected area',
            'intercontinental treaties or conventions nature protected area',
          ],
          'osm:tags': {
            boundary: 'protected_area',
            protect_class: '98',
            protection_title: 'world_heritage_convention',
            ref: '373',
            website: 'https://whc.unesco.org/en/list/373',
            heritage: '1',
            designation: 'world_heritage_convention',
            type: 'boundary',
          },
          text_en: 'Stonehenge Avebury and Associated Sites WHS',
        },
        {
          ref: 'osm:r62149',
          id: 'country.185',
          text: 'United Kingdom',
          country_code: 'gb',
          wikidata: 'Q145',
          kind: 'admin_area',
          'osm:place_type': 'country',
          language: 'en',
          text_en: 'United Kingdom',
          language_en: 'en',
        },
        {
          ref: 'osm:n25871341',
          id: 'continental_marine.1',
          text: 'Europe',
          wikidata: 'Q46',
          categories: ['continent'],
          language: 'en',
          'osm:tags': {
            population: '739165030',
            place: 'continent',
            wikipedia: 'eo:Eŭropo',
            sqkm: '10180000',
          },
          text_en: 'Europe',
          language_en: 'en',
        },
      ],
      text_en: 'Amesbury',
      place_name_en: 'Amesbury, Wiltshire, United Kingdom',
    },
    {
      type: 'Feature',
      properties: {
        ref: 'osm:r57533',
        country_code: 'gb',
        wikidata: 'Q21694746',
        kind: 'admin_area',
        'osm:place_type': 'county',
        place_type_name: ['county'],
      },
      geometry: {
        type: 'Point',
        coordinates: [-2.208007201552391, 51.320030588648585],
      },
      bbox: [
        -2.365592010319233, 50.94498601568751, -1.4857268705964088,
        51.703141742082984,
      ],
      center: [-2.208007201552391, 51.320030588648585],
      place_name: 'Wiltshire, United Kingdom',
      place_type: ['county'],
      relevance: 1,
      id: 'county.2616',
      text: 'Wiltshire',
      place_type_name: ['county'],
      context: [
        {
          ref: 'osm:r58447',
          id: 'region.1220',
          text: 'England',
          country_code: 'gb',
          wikidata: 'Q21',
          kind: 'admin_area',
          'osm:place_type': 'state',
          language: 'en',
          text_en: 'England',
          language_en: 'en',
        },
        {
          ref: 'osm:r9345787',
          id: 'major_landform.4552872',
          text: 'Stonehenge Avebury and Associated Sites WHS',
          country_code: 'gb',
          categories: [
            'protected area',
            'intercontinental treaties or conventions nature protected area',
          ],
          'osm:tags': {
            boundary: 'protected_area',
            protect_class: '98',
            protection_title: 'world_heritage_convention',
            ref: '373',
            website: 'https://whc.unesco.org/en/list/373',
            heritage: '1',
            designation: 'world_heritage_convention',
            type: 'boundary',
          },
          text_en: 'Stonehenge Avebury and Associated Sites WHS',
        },
        {
          ref: 'osm:r62149',
          id: 'country.185',
          text: 'United Kingdom',
          country_code: 'gb',
          wikidata: 'Q145',
          kind: 'admin_area',
          'osm:place_type': 'country',
          language: 'en',
          text_en: 'United Kingdom',
          language_en: 'en',
        },
        {
          ref: 'osm:n25871341',
          id: 'continental_marine.1',
          text: 'Europe',
          wikidata: 'Q46',
          categories: ['continent'],
          language: 'en',
          'osm:tags': {
            population: '739165030',
            place: 'continent',
            wikipedia: 'eo:Eŭropo',
            sqkm: '10180000',
          },
          text_en: 'Europe',
          language_en: 'en',
        },
      ],
      language: 'en',
      text_en: 'Wiltshire',
      language_en: 'en',
      place_name_en: 'Wiltshire, United Kingdom',
    },
    {
      type: 'Feature',
      properties: {
        ref: 'osm:r58447',
        country_code: 'gb',
        wikidata: 'Q21',
        kind: 'admin_area',
        'osm:place_type': 'state',
        place_type_name: ['country'],
      },
      geometry: {
        type: 'Point',
        coordinates: [-1.2649063020944595, 52.53102140792826],
      },
      bbox: [
        -6.704740673303604, 49.67400019103503, 2.0919040963053708,
        55.91700006650206,
      ],
      center: [-1.2649063020944595, 52.53102140792826],
      place_name: 'England, United Kingdom',
      place_type: ['region'],
      relevance: 1,
      id: 'region.1220',
      text: 'England',
      place_type_name: ['country'],
      context: [
        {
          ref: 'osm:r9345787',
          id: 'major_landform.4552872',
          text: 'Stonehenge Avebury and Associated Sites WHS',
          country_code: 'gb',
          categories: [
            'protected area',
            'intercontinental treaties or conventions nature protected area',
          ],
          'osm:tags': {
            boundary: 'protected_area',
            protect_class: '98',
            protection_title: 'world_heritage_convention',
            ref: '373',
            website: 'https://whc.unesco.org/en/list/373',
            heritage: '1',
            designation: 'world_heritage_convention',
            type: 'boundary',
          },
          text_en: 'Stonehenge Avebury and Associated Sites WHS',
        },
        {
          ref: 'osm:r62149',
          id: 'country.185',
          text: 'United Kingdom',
          country_code: 'gb',
          wikidata: 'Q145',
          kind: 'admin_area',
          'osm:place_type': 'country',
          language: 'en',
          text_en: 'United Kingdom',
          language_en: 'en',
        },
        {
          ref: 'osm:n25871341',
          id: 'continental_marine.1',
          text: 'Europe',
          wikidata: 'Q46',
          categories: ['continent'],
          language: 'en',
          'osm:tags': {
            population: '739165030',
            place: 'continent',
            wikipedia: 'eo:Eŭropo',
            sqkm: '10180000',
          },
          text_en: 'Europe',
          language_en: 'en',
        },
      ],
      language: 'en',
      text_en: 'England',
      language_en: 'en',
      place_name_en: 'England, United Kingdom',
    },
  ],
  query: [-1.826179271164392, 51.17884907055111],
  attribution:
    '<a href="https://www.maptiler.com/copyright/" target="_blank">&copy; MapTiler</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>',
} as unknown as GeocodingSearchResult;

export const GERMANY_15936: GeocodingSearchResult = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      properties: {
        ref: 'ggp:15936',
        country_code: 'de',
        place_type_name: ['Postleitzahl'],
      },
      geometry: {
        type: 'Point',
        coordinates: [13.42731414525565, 51.88136795315022],
      },
      bbox: [13.2715582, 51.7907328, 13.5822093, 51.9771469],
      center: [13.42731414525565, 51.88136795315022],
      place_name: '15936, Deutschland',
      place_type: ['postal_code'],
      relevance: 1,
      id: 'postal_code.1822499',
      text: '15936',
      place_type_name: ['Postleitzahl'],
      context: [
        {
          ref: 'osm:r4568621',
          id: 'municipal_district.18862',
          text: 'Buckow',
          country_code: 'de',
          wikidata: 'Q25158531',
          kind: 'admin_area',
          'osm:place_type': 'hamlet',
          text_de: 'Buckow',
        },
        {
          ref: 'osm:r422441',
          id: 'municipality.59041',
          text: 'Dahme/Mark',
          country_code: 'de',
          wikidata: 'Q622572',
          kind: 'admin_area',
          'osm:place_type': 'town',
          text_de: 'Dahme/Mark',
        },
        {
          ref: 'osm:r422442',
          id: 'joint_municipality.4390',
          text: 'Dahme/Mark',
          country_code: 'de',
          wikidata: 'Q455502',
          kind: 'admin_area',
          text_de: 'Dahme/Mark',
        },
        {
          ref: 'osm:r62364',
          id: 'county.6301',
          text: 'Teltow-Fläming',
          country_code: 'de',
          wikidata: 'Q6146',
          kind: 'admin_area',
          'osm:place_type': 'municipality',
          language: 'de',
          text_de: 'Teltow-Fläming',
          language_de: 'de',
        },
        {
          ref: 'osm:r62504',
          id: 'region.1901',
          text: 'Brandenburg',
          country_code: 'de',
          wikidata: 'Q1208',
          kind: 'admin_area',
          'osm:place_type': 'state',
          language: 'de',
          text_de: 'Brandenburg',
          language_de: 'de',
        },
        {
          ref: 'osm:w570780695',
          id: 'major_landform.2236363',
          text: 'Kessel-Berge',
          country_code: 'de',
          categories: ['ridge'],
          'osm:tags': {
            natural: 'ridge',
          },
          text_de: 'Kessel-Berge',
        },
        {
          ref: 'osm:r51477',
          id: 'country.194',
          text: 'Deutschland',
          country_code: 'de',
          wikidata: 'Q183',
          kind: 'admin_area',
          'osm:place_type': 'country',
          language: 'de',
          text_de: 'Deutschland',
          language_de: 'de',
        },
        {
          ref: 'osm:n25871341',
          id: 'continental_marine.1',
          text: 'Europa',
          wikidata: 'Q46',
          categories: ['continent'],
          language: 'de',
          'osm:tags': {
            population: '739165030',
            place: 'continent',
            wikipedia: 'eo:Eŭropo',
            sqkm: '10180000',
          },
          text_de: 'Europa',
          language_de: 'de',
        },
      ],
      text_de: '15936',
      place_name_de:
        '15936, Buckow, Dahme/Mark, Dahme/Mark, Teltow-Fläming, Brandenburg, Deutschland',
    },
    {
      type: 'Feature',
      properties: {
        ref: 'osm:r422441',
        country_code: 'de',
        wikidata: 'Q622572',
        kind: 'admin_area',
        'osm:place_type': 'town',
        place_type_name: ['Gemeinde'],
      },
      geometry: {
        type: 'Point',
        coordinates: [13.428490161895752, 51.86993939794441],
      },
      bbox: [
        13.271485045552254, 51.79076203464216, 13.568105846643448,
        51.97714697315068,
      ],
      center: [13.428490161895752, 51.86993939794441],
      place_name: 'Dahme/Mark, Brandenburg, Deutschland',
      place_type: ['municipality'],
      relevance: 1,
      id: 'municipality.59041',
      text: 'Dahme/Mark',
      place_type_name: ['Gemeinde'],
      context: [
        {
          ref: 'osm:r422442',
          id: 'joint_municipality.4390',
          text: 'Dahme/Mark',
          country_code: 'de',
          wikidata: 'Q455502',
          kind: 'admin_area',
          text_de: 'Dahme/Mark',
        },
        {
          ref: 'osm:r62364',
          id: 'county.6301',
          text: 'Teltow-Fläming',
          country_code: 'de',
          wikidata: 'Q6146',
          kind: 'admin_area',
          'osm:place_type': 'municipality',
          language: 'de',
          text_de: 'Teltow-Fläming',
          language_de: 'de',
        },
        {
          ref: 'osm:r62504',
          id: 'region.1901',
          text: 'Brandenburg',
          country_code: 'de',
          wikidata: 'Q1208',
          kind: 'admin_area',
          'osm:place_type': 'state',
          language: 'de',
          text_de: 'Brandenburg',
          language_de: 'de',
        },
        {
          ref: 'osm:w570780695',
          id: 'major_landform.2236363',
          text: 'Kessel-Berge',
          country_code: 'de',
          categories: ['ridge'],
          'osm:tags': {
            natural: 'ridge',
          },
          text_de: 'Kessel-Berge',
        },
        {
          ref: 'osm:r51477',
          id: 'country.194',
          text: 'Deutschland',
          country_code: 'de',
          wikidata: 'Q183',
          kind: 'admin_area',
          'osm:place_type': 'country',
          language: 'de',
          text_de: 'Deutschland',
          language_de: 'de',
        },
        {
          ref: 'osm:n25871341',
          id: 'continental_marine.1',
          text: 'Europa',
          wikidata: 'Q46',
          categories: ['continent'],
          language: 'de',
          'osm:tags': {
            population: '739165030',
            place: 'continent',
            wikipedia: 'eo:Eŭropo',
            sqkm: '10180000',
          },
          text_de: 'Europa',
          language_de: 'de',
        },
      ],
      text_de: 'Dahme/Mark',
      place_name_de: 'Dahme/Mark, Brandenburg, Deutschland',
    },
    {
      type: 'Feature',
      properties: {
        ref: 'osm:r62364',
        country_code: 'de',
        wikidata: 'Q6146',
        kind: 'admin_area',
        'osm:place_type': 'municipality',
        place_type_name: ['Landkreis'],
      },
      geometry: {
        type: 'Point',
        coordinates: [13.174187913537025, 52.09020468038767],
      },
      bbox: [
        12.769923023879526, 51.79076203464216, 13.652763068675995,
        52.41172416284917,
      ],
      center: [13.174187913537025, 52.09020468038767],
      place_name: 'Teltow-Fläming, Brandenburg, Deutschland',
      place_type: ['county'],
      relevance: 1,
      id: 'county.6301',
      text: 'Teltow-Fläming',
      place_type_name: ['Landkreis'],
      context: [
        {
          ref: 'osm:r62504',
          id: 'region.1901',
          text: 'Brandenburg',
          country_code: 'de',
          wikidata: 'Q1208',
          kind: 'admin_area',
          'osm:place_type': 'state',
          language: 'de',
          text_de: 'Brandenburg',
          language_de: 'de',
        },
        {
          ref: 'osm:w570780695',
          id: 'major_landform.2236363',
          text: 'Kessel-Berge',
          country_code: 'de',
          categories: ['ridge'],
          'osm:tags': {
            natural: 'ridge',
          },
          text_de: 'Kessel-Berge',
        },
        {
          ref: 'osm:r51477',
          id: 'country.194',
          text: 'Deutschland',
          country_code: 'de',
          wikidata: 'Q183',
          kind: 'admin_area',
          'osm:place_type': 'country',
          language: 'de',
          text_de: 'Deutschland',
          language_de: 'de',
        },
        {
          ref: 'osm:n25871341',
          id: 'continental_marine.1',
          text: 'Europa',
          wikidata: 'Q46',
          categories: ['continent'],
          language: 'de',
          'osm:tags': {
            population: '739165030',
            place: 'continent',
            wikipedia: 'eo:Eŭropo',
            sqkm: '10180000',
          },
          text_de: 'Europa',
          language_de: 'de',
        },
      ],
      language: 'de',
      text_de: 'Teltow-Fläming',
      language_de: 'de',
      place_name_de: 'Teltow-Fläming, Brandenburg, Deutschland',
    },
    {
      type: 'Feature',
      properties: {
        ref: 'osm:r62504',
        country_code: 'de',
        wikidata: 'Q1208',
        kind: 'admin_area',
        'osm:place_type': 'state',
        place_type_name: ['Bundesland'],
      },
      geometry: {
        type: 'Point',
        coordinates: [13.059139586985111, 52.40093090931887],
      },
      bbox: [
        11.265772394835949, 51.3590642048414, 14.765815772116186,
        53.55909077950389,
      ],
      center: [13.059139586985111, 52.40093090931887],
      place_name: 'Brandenburg, Deutschland',
      place_type: ['region'],
      relevance: 1,
      id: 'region.1901',
      text: 'Brandenburg',
      place_type_name: ['Bundesland'],
      context: [
        {
          ref: 'osm:w570780695',
          id: 'major_landform.2236363',
          text: 'Kessel-Berge',
          country_code: 'de',
          categories: ['ridge'],
          'osm:tags': {
            natural: 'ridge',
          },
          text_de: 'Kessel-Berge',
        },
        {
          ref: 'osm:r51477',
          id: 'country.194',
          text: 'Deutschland',
          country_code: 'de',
          wikidata: 'Q183',
          kind: 'admin_area',
          'osm:place_type': 'country',
          language: 'de',
          text_de: 'Deutschland',
          language_de: 'de',
        },
        {
          ref: 'osm:n25871341',
          id: 'continental_marine.1',
          text: 'Europa',
          wikidata: 'Q46',
          categories: ['continent'],
          language: 'de',
          'osm:tags': {
            population: '739165030',
            place: 'continent',
            wikipedia: 'eo:Eŭropo',
            sqkm: '10180000',
          },
          text_de: 'Europa',
          language_de: 'de',
        },
      ],
      language: 'de',
      text_de: 'Brandenburg',
      language_de: 'de',
      place_name_de: 'Brandenburg, Deutschland',
    },
  ],
  query: [13.404671781825982, 51.94999513721038],
  attribution:
    '<a href="https://www.maptiler.com/copyright/" target="_blank">&copy; MapTiler</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>',
} as unknown as GeocodingSearchResult;
