// This file is generated by generate.ts
import en from './en.json'; export { en };
import el from './el.json'; export { el };
import de from './de.json'; export { de };
import deInformal from './de@informal.json'; export { deInformal };
import nl from './nl.json'; export { nl };
import pt from './pt.json'; export { pt };
import it from './it.json'; export { it };
import ru from './ru.json'; export { ru };
import deEasy from './de@easy.json'; export { deEasy };
