// This file is generated by generate.ts
import en from "./en.json" with { type: "json" };
export { en };
import el from "./el.json" with { type: "json" };
export { el };
import de from "./de.json" with { type: "json" };
export { de };
import deInformal from "./de@informal.json" with { type: "json" };
export { deInformal };
import nl from "./nl.json" with { type: "json" };
export { nl };
import pt from "./pt.json" with { type: "json" };
export { pt };
import it from "./it.json" with { type: "json" };
export { it };
import ru from "./ru.json" with { type: "json" };
export { ru };
import deEasy from "./de@easy.json" with { type: "json" };
export { deEasy };
