// This file is generated by generate.js
export * as 'en' from './en.cjs';
export * as 'de' from './de.cjs';
export * as 'de@informal' from './de@informal.cjs';
export * as 'pt' from './pt.cjs';
export * as 'it' from './it.cjs';
export * as 'ru' from './ru.cjs';
export * as 'nl' from './nl.cjs';
export * as 'de@easy' from './de@easy.cjs';
