runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: yarn
        node-version: 20
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x.x
        cache: true
    - name: Install node dependencies
      run: yarn install
    # re-enable when the cache server is running stably again
    # - name: Install deno dependencies
    #   run: yarn deno:cache
    - name: Build
      run: yarn build
