runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: yarn
        node-version: 22.x
    - name: Install dependencies
      run: yarn install
      shell: bash
    - name: Build common
      run: yarn workspace @beabee/beabee-common build
      shell: bash
    - name: Build core
      run: yarn workspace @beabee/core build
      shell: bash
