yarnPath: .yarn/releases/yarn-4.2.2.cjs
nodeLinker: "node-modules"
# Workaround for Error: [vite]: Rollup failed to resolve import "@tiptap/pm/state"
packageExtensions:
  "@tiptap/starter-kit@*":
    peerDependencies:
      "@tiptap/pm": "*"
  "vite-plugin-pages@*":
    dependencies:
      "@vue/compiler-sfc": "*"
