services:
  db:
    extends:
      file: docker-compose.yml
      service: db
    ports:
      - ${DB_PORT}:5432

  mail:
    extends:
      file: docker-compose.yml
      service: mail
    ports:
      - ${MAIL_PORT}:1080

  app:
    extends:
      file: docker-compose.yml
      service: app
    env_file:
      - .env
      - .env.test

  api_app:
    extends:
      file: docker-compose.yml
      service: api_app
    env_file:
      - .env
      - .env.test

  webhook_app:
    extends:
      file: docker-compose.yml
      service: webhook_app
    env_file:
      - .env
      - .env.test

  cron_app:
    extends:
      file: docker-compose.yml
      service: cron_app
    env_file:
      - .env
      - .env.test

  minio:
    extends:
      file: docker-compose.yml
      service: minio

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend

  app_router:
    extends:
      file: docker-compose.yml
      service: app_router
    ports:
      - ${ROUTER_PORT}:80
    depends_on:
      - api_app
      - webhook_app

  migration:
    extends:
      file: docker-compose.yml
      service: migration
    env_file:
      - .env
      - .env.test

  stripe_cli:
    extends:
      file: docker-compose.yml
      service: stripe_cli
    environment:
      - STRIPE_API_KEY=${BEABEE_STRIPE_SECRETKEY}
      - STRIPE_DEVICE_NAME=beabee-test-docker-container

volumes:
  db_data:
  upload_data:
  minio_data:
