services:
  db:
    extends:
      file: docker-compose.yml
      service: db
    ports:
      - ${DB_PORT}:5432

  mail:
    extends:
      file: docker-compose.yml
      service: mail
    ports:
      - ${MAIL_PORT}:1080

  app:
    extends:
      file: docker-compose.yml
      service: app
    env_file:
      - .env
      - .env.test

  api_app:
    extends:
      file: docker-compose.yml
      service: api_app
    env_file:
      - .env
      - .env.test

  webhook_app:
    extends:
      file: docker-compose.yml
      service: webhook_app
    env_file:
      - .env
      - .env.test

  cron_app:
    extends:
      file: docker-compose.yml
      service: cron_app
    env_file:
      - .env
      - .env.test

  minio:
    extends:
      file: docker-compose.yml
      service: minio
    ports:
      - "${BEABEE_MINIO_PORT_ADMIN:-9002}:9000" # Admin port for debugging, not for production
      - "${BEABEE_MINIO_PORT_CONSOLE:-9003}:9001" # Console port (Admin UI), not for production
    environment:
      MINIO_ROOT_USER: ${BEABEE_MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${BEABEE_MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_REGION: ${BEABEE_MINIO_REGION:-us-east-1}
      BEABEE_MINIO_BUCKET: ${BEABEE_MINIO_BUCKET:-uploads}
      BEABEE_MINIO_ENDPOINT: ${BEABEE_MINIO_ENDPOINT:-http://minio:9000}

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    env_file:
      - ./apps/frontend/.env
      - ./apps/frontend/.env.test

  app_router:
    extends:
      file: docker-compose.yml
      service: app_router
    environment:
      LEGACY_APP_COOKIE_DOMAIN: ${BEABEE_COOKIE_DOMAIN}
      TRUSTED_ORIGINS: ${BEABEE_TRUSTEDORIGINS-}
    ports:
      - ${ROUTER_PORT}:80

  migration:
    extends:
      file: docker-compose.yml
      service: migration
    env_file:
      - .env
      - .env.test

  stripe_cli:
    extends:
      file: docker-compose.yml
      service: stripe_cli
    environment:
      - STRIPE_API_KEY=${BEABEE_STRIPE_SECRETKEY}
      - STRIPE_DEVICE_NAME=beabee-test-docker-container

volumes:
  db_data:
  upload_data:
  minio_data:
