# version: "3.4"

x-base-app: &base-app
  image: beabee/beabee:local
  volumes:
    # App itself
    - ./dist:/opt/apps/backend/dist
    # Packages
    - ../../packages/common/dist:/opt/packages/common/dist
    - ../../packages/config/dist:/opt/packages/config/dist
    - ../../packages/core/dist:/opt/packages/core/dist
    - ../../packages/locales/dist:/opt/packages/locales/dist
    - ../../packages/models/dist:/opt/packages/models/dist
    - ../../packages/task-runner/dist:/opt/packages/task-runner/dist
  env_file:
    - .env
  environment:
    NODE_ENV: development

services:
  db:
    image: postgres:13.9
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: membership_system
      POSTGRES_PASSWORD: membership_system
      POSTGRES_DB: membership_system
    ports:
      - 6543:5432 # To connect to the database from the host machine

  mail:
    image: maildev/maildev:2.1.0
    ports:
      - ${MAIL_PORT}:1080

  app: *base-app

  api_app:
    <<: *base-app
    command: yarn start:api:prod

  webhook_app:
    <<: *base-app
    working_dir: /opt/apps/backend
    command: yarn start:webhooks:prod

  img_upload_app:
    image: beabee/pictshare:v0.1.1
    environment:
      URL: ${BEABEE_AUDIENCE}/uploads/
      CONTENTCONTROLLERS: IMAGE,TEXT
    init: true
    volumes:
      - upload_data:/var/www/data

  cron:
    <<: *base-app
    user: root
    command: crond -f -d 7
    # debian: command: "cron -f"
    init: true

  router:
    image: beabee/router:local
    volumes:
      - ./dist/static:/opt/dist/static:ro
    ports:
      - ${MAIN_PORT}:80

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  task-runner-dashboard:
    # build:
    #   context: ../..
    #   dockerfile: ./apps/task-runner-dashboard/Dockerfile
    image: beabee/task-runner-dashboard:local
    environment:
      TASK_RUNNER_DASHBOARD_PORT: 3004
      TASK_RUNNER_REDIS_HOST: redis
      TASK_RUNNER_REDIS_PORT: 6379
      TASK_RUNNER_DASHBOARD_ROUTE_PREFIX: /
    ports:
      - 3004:3004
    volumes:
      # App itself
      - ../../apps/task-runner-dashboard/dist:/opt/apps/task-runner-dashboard/dist

  task-runner-worker:
    # build:
    #   context: ../..
    #   dockerfile: ./apps/task-runner-worker/Dockerfile
    image: beabee/task-runner-worker:local
    environment:
      TASK_RUNNER_REDIS_HOST: redis
      TASK_RUNNER_REDIS_PORT: 6379
    ports:
      - 3005:3005
    volumes:
      # App itself
      - ../../apps/task-runner-worker/dist:/opt/apps/task-runner-worker/dist

volumes:
  db_data:
  upload_data:
  redis_data:
