// Auto-generated by `@beabee/dev-cli generate-class-index`. Do not edit by hand.
import { ApiKey } from './models/ApiKey.js';
import { Callout } from './models/Callout.js';
import { CalloutResponse } from './models/CalloutResponse.js';
import { CalloutResponseComment } from './models/CalloutResponseComment.js';
import { CalloutResponseSegment } from './models/CalloutResponseSegment.js';
import { CalloutResponseTag } from './models/CalloutResponseTag.js';
import { CalloutReviewer } from './models/CalloutReviewer.js';
import { CalloutTag } from './models/CalloutTag.js';
import { CalloutVariant } from './models/CalloutVariant.js';
import { Contact } from './models/Contact.js';
import { ContactContribution } from './models/ContactContribution.js';
import { ContactMfa } from './models/ContactMfa.js';
import { ContactProfile } from './models/ContactProfile.js';
import { ContactRole } from './models/ContactRole.js';
import { ContactTag } from './models/ContactTag.js';
import { ContactTagAssignment } from './models/ContactTagAssignment.js';
import { Content } from './models/Content.js';
import { Email } from './models/Email.js';
import { EmailMailing } from './models/EmailMailing.js';
import { Export } from './models/Export.js';
import { ExportItem } from './models/ExportItem.js';
import { GiftFlow } from './models/GiftFlow.js';
import { GiftForm } from './models/GiftForm.js';
import { ItemWithStatus } from './models/ItemWithStatus.js';
import { Notice } from './models/Notice.js';
import { Option } from './models/Option.js';
import { PageSettings } from './models/PageSettings.js';
import { Password } from './models/Password.js';
import { Payment } from './models/Payment.js';
import { PaymentFlow } from './models/PaymentFlow.js';
import { Project } from './models/Project.js';
import { ProjectContact } from './models/ProjectContact.js';
import { ProjectEngagement } from './models/ProjectEngagement.js';
import { Referral } from './models/Referral.js';
import { ReferralGift } from './models/ReferralGift.js';
import { ResetSecurityFlow } from './models/ResetSecurityFlow.js';
import { Segment } from './models/Segment.js';
import { SegmentContact } from './models/SegmentContact.js';
import { SegmentOngoingEmail } from './models/SegmentOngoingEmail.js';
import { SignupFlow } from './models/SignupFlow.js';

export const entities = [
  ApiKey,
  Callout,
  CalloutResponse,
  CalloutResponseComment,
  CalloutResponseSegment,
  CalloutResponseTag,
  CalloutReviewer,
  CalloutTag,
  CalloutVariant,
  Contact,
  ContactContribution,
  ContactMfa,
  ContactProfile,
  ContactRole,
  ContactTag,
  ContactTagAssignment,
  Content,
  Email,
  EmailMailing,
  Export,
  ExportItem,
  GiftFlow,
  GiftForm,
  ItemWithStatus,
  Notice,
  Option,
  PageSettings,
  Password,
  Payment,
  PaymentFlow,
  Project,
  ProjectContact,
  ProjectEngagement,
  Referral,
  ReferralGift,
  ResetSecurityFlow,
  Segment,
  SegmentContact,
  SegmentOngoingEmail,
  SignupFlow,
];
