// Auto-generated by `@beabee/dev-cli generate-class-index`. Do not edit by hand.
import { SessionTable1616677358190 } from './migrations/1616677358190-SessionTable.js';
import { InitDatabase1616679012431 } from './migrations/1616679012431-InitDatabase.js';
import { AddSegmentOrder1616693016456 } from './migrations/1616693016456-AddSegmentOrder.js';
import { AddDefaultSegments1616694307645 } from './migrations/1616694307645-AddDefaultSegments.js';
import { AddSegmentNewsletterListId1618488866877 } from './migrations/1618488866877-AddSegmentNewsletterListId.js';
import { RenameListIdToTag1619099359790 } from './migrations/1619099359790-RenameListIdToTag.js';
import { OptionalMemberCodes1619113429486 } from './migrations/1619113429486-OptionalMemberCodes.js';
import { DeliveryOptInDefault1620225385309 } from './migrations/1620225385309-DeliveryOptInDefault.js';
import { AddNewsletterFieldsToProfile1620381066389 } from './migrations/1620381066389-AddNewsletterFieldsToProfile.js';
import { AddEmailAndPasswordToJoinFlow1621513644609 } from './migrations/1621513644609-AddEmailAndPasswordToJoinFlow.js';
import { AddPollResponsePassword1624370860614 } from './migrations/1624370860614-AddPollResponsePassword.js';
import { RenameJoinFlowAmountToMonthlyAmount1624469115041 } from './migrations/1624469115041-RenameJoinFlowAmountToMonthlyAmount.js';
import { ConvertMonthlyAmountToReal1624469629114 } from './migrations/1624469629114-ConvertMonthlyAmountToReal.js';
import { AddMemberActivatedField1626344080098 } from './migrations/1626344080098-AddMemberActivatedField.js';
import { AddButtonText1632397910432 } from './migrations/1632397910432-AddButtonText.js';
import { UseEmailInSegmentOngoingEmail1632931118456 } from './migrations/1632931118456-UseEmailInSegmentOngoingEmail.js';
import { AddContent1632994213635 } from './migrations/1632994213635-AddContent.js';
import { AddExcerptAndImageToPoll1634125137636 } from './migrations/1634125137636-AddExcerptAndImageToPoll.js';
import { AddResetPasswordFlow1634737662792 } from './migrations/1634737662792-AddResetPasswordFlow.js';
import { RemoveRestartFlow1635350051303 } from './migrations/1635350051303-RemoveRestartFlow.js';
import { FormatEmailBody1638448727069 } from './migrations/1638448727069-FormatEmailBody.js';
import { RemovePasswordResetCode1638975520912 } from './migrations/1638975520912-RemovePasswordResetCode.js';
import { JoinFlowRedirectFlowOptional1639075139123 } from './migrations/1639075139123-JoinFlowRedirectFlowOptional.js';
import { MigrateJoinFlowOptions1639655491472 } from './migrations/1639655491472-MigrateJoinFlowOptions.js';
import { ChangeDefaultNewsletterStatus1639665377317 } from './migrations/1639665377317-ChangeDefaultNewsletterStatus.js';
import { AddAllowMultiplePollResponses1639760915487 } from './migrations/1639760915487-AddAllowMultiplePollResponses.js';
import { UnifyItemStatuses1646649540217 } from './migrations/1646649540217-UnifyItemStatuses.js';
import { MakeImageFieldNonNullable1646649663368 } from './migrations/1646649663368-MakeImageFieldNonNullable.js';
import { ConvertAllPollsToBuilderTemplate1648725496337 } from './migrations/1648725496337-ConvertAllPollsToBuilderTemplate.js';
import { UpdateDefaultSegments1650535261889 } from './migrations/1650535261889-UpdateDefaultSegments.js';
import { AddEmptyGeneralContent1650535712817 } from './migrations/1650535712817-AddEmptyGeneralContent.js';
import { AddDefaultContent1650537835623 } from './migrations/1650537835623-AddDefaultContent.js';
import { AddPaymentMethodToJoinForm1650900384747 } from './migrations/1650900384747-AddPaymentMethodToJoinForm.js';
import { NonNullRedirectFlowId1650904701374 } from './migrations/1650904701374-NonNullRedirectFlowId.js';
import { AddContactsContent1651058503997 } from './migrations/1651058503997-AddContactsContent.js';
import { RenameRedirectFlowToPaymentFlow1651068668585 } from './migrations/1651068668585-RenameRedirectFlowToPaymentFlow.js';
import { AddUrlsToJoinFlow1652115873327 } from './migrations/1652115873327-AddUrlsToJoinFlow.js';
import { AddShareFieldsToPoll1652276361695 } from './migrations/1652276361695-AddShareFieldsToPoll.js';
import { RenameGoCardlessToAutomatic1652285362376 } from './migrations/1652285362376-RenameGoCardlessToAutomatic.js';
import { AddPaymentData1652966714320 } from './migrations/1652966714320-AddPaymentData.js';
import { AddPayment1653488390953 } from './migrations/1653488390953-AddPayment.js';
import { MigratePaymentTables1653495059460 } from './migrations/1653495059460-MigratePaymentTables.js';
import { RemoveNextContributionAmount1655199299904 } from './migrations/1655199299904-RemoveNextContributionAmount.js';
import { MigrateManualPaymentData1655393209607 } from './migrations/1655393209607-MigrateManualPaymentData.js';
import { OptionalFromEmailFields1656001166095 } from './migrations/1656001166095-OptionalFromEmailFields.js';
import { AddOptionalFirstAndLastNameToJoinFlow1656347461817 } from './migrations/1656347461817-AddOptionalFirstAndLastNameToJoinFlow.js';
import { ConvertPaymentStatuses1656935238800 } from './migrations/1656935238800-ConvertPaymentStatuses.js';
import { OptionalButtonText1659968561064 } from './migrations/1659968561064-OptionalButtonText.js';
import { AddShareContent1660235362253 } from './migrations/1660235362253-AddShareContent.js';
import { AddEmailContent1660562732237 } from './migrations/1660562732237-AddEmailContent.js';
import { FixSegmentRuleGroups1665070450970 } from './migrations/1665070450970-FixSegmentRuleGroups.js';
import { UpdateRuleValues1667846310950 } from './migrations/1667846310950-UpdateRuleValues.js';
import { RenameModels1670242308699 } from './migrations/1670242308699-RenameModels.js';
import { RenameModelReferences1670257047310 } from './migrations/1670257047310-RenameModelReferences.js';
import { RenameAutoGeneratedKeyIds1670258044685 } from './migrations/1670258044685-RenameAutoGeneratedKeyIds.js';
import { RenamePollModelReferences1670260399264 } from './migrations/1670260399264-RenamePollModelReferences.js';
import { AddCalloutResponseBucket1676460782435 } from './migrations/1676460782435-AddCalloutResponseBucket.js';
import { FixContactProfileKeys1676623400914 } from './migrations/1676623400914-FixContactProfileKeys.js';
import { AddCalloutTag1676654870090 } from './migrations/1676654870090-AddCalloutTag.js';
import { AddCalloutResponseTag1676655715419 } from './migrations/1676655715419-AddCalloutResponseTag.js';
import { AddCalloutResponseNumber1678287340165 } from './migrations/1678287340165-AddCalloutResponseNumber.js';
import { MakeBucketNonNullable1678358909981 } from './migrations/1678358909981-MakeBucketNonNullable.js';
import { AddCalloutResponseAssignee1678884024926 } from './migrations/1678884024926-AddCalloutResponseAssignee.js';
import { AddCalloutResponseCommentTable1678888737358 } from './migrations/1678888737358-AddCalloutResponseCommentTable.js';
import { AddUpdatedAtToCalloutResponseComment1678898590335 } from './migrations/1678898590335-AddUpdatedAtToCalloutResponseComment.js';
import { ModifyCommentForeignKeyRestraints1678974773924 } from './migrations/1678974773924-ModifyCommentForeignKeyRestraints.js';
import { RemoveDefaultFormSchema1679064034052 } from './migrations/1679064034052-RemoveDefaultFormSchema.js';
import { AddApiKeyModel1685528456765 } from './migrations/1685528456765-AddApiKeyModel.js';
import { UpdateApiKeyModel1686233596892 } from './migrations/1686233596892-UpdateApiKeyModel.js';
import { ApiKeyDescriptioNotNull1686233847551 } from './migrations/1686233847551-ApiKeyDescriptioNotNull.js';
import { AddCalloutMapSchema1690389664790 } from './migrations/1690389664790-AddCalloutMapSchema.js';
import { AddUploadFlow1691577150283 } from './migrations/1691577150283-AddUploadFlow.js';
import { AddUploadUsedCol1691597308499 } from './migrations/1691597308499-AddUploadUsedCol.js';
import { AddCalloutResponseViewSchema1692289610630 } from './migrations/1692289610630-AddCalloutResponseViewSchema.js';
import { PaymentDataCancelledAt1694009247783 } from './migrations/1694009247783-PaymentDataCancelledAt.js';
import { RenamePollOptions1696506058706 } from './migrations/1696506058706-RenamePollOptions.js';
import { UpdateGCNextAmount1696600862719 } from './migrations/1696600862719-UpdateGCNextAmount.js';
import { NewCalloutSlideSchema1697020619835 } from './migrations/1697020619835-NewCalloutSlideSchema.js';
import { DeleteOld2FA1698338165267 } from './migrations/1698338165267-DeleteOld2FA.js';
import { AddContactMfa1698418165066 } from './migrations/1698418165066-AddContactMfa.js';
import { AddApiKeyExpiryDate1698938717666 } from './migrations/1698938717666-AddApiKeyExpiryDate.js';
import { RenameResetPasswordFlowToResetSecurityFlow1700131647453 } from './migrations/1700131647453-RenameToResetSecurityFlow.js';
import { UpdateIndexes1701968585255 } from './migrations/1701968585255-UpdateIndexes.js';
import { UpdateCalloutTag1703247945472 } from './migrations/1703247945472-UpdateCalloutTag.js';
import { ConvertChargeDateToDate1706113195469 } from './migrations/1706113195469-ConvertChargeDateToDate.js';
import { AddCalloutId1708615794655 } from './migrations/1708615794655-AddCalloutId.js';
import { AddCalloutVariant1708685548000 } from './migrations/1708685548000-AddCalloutVariant.js';
import { ChangeVariantLocaleToName1708688873027 } from './migrations/1708688873027-ChangeVariantLocaleToName.js';
import { AddCalloutCaptchaField1709217978680 } from './migrations/1709217978680-AddCalloutCaptchaField.js';
import { AddCalloutVariantFormTexts1709297783048 } from './migrations/1709297783048-AddCalloutVariantFormTexts.js';
import { AddExtraJoinFormFields1712158796671 } from './migrations/1712158796671-AddExtraJoinFormFields.js';
import { RemoveJoinFormBillingAddress1712163090314 } from './migrations/1712163090314-RemoveJoinFormBillingAddress.js';
import { RenamePaymentDataToContactContribution1713373413805 } from './migrations/1713373413805-RenamePaymentDataToContactContribution.js';
import { FlattenContributionData1713434533086 } from './migrations/1713434533086-FlattenContributionData.js';
import { CalloutChannels1715184967411 } from './migrations/1715184967411-callout-channels.js';
import { ImproveContactFieldTypes1715355140741 } from './migrations/1715355140741-ImproveContactFieldTypes.js';
import { RemoveResponseIsPartialFlag1729522899474 } from './migrations/1729522899474-RemoveResponseIsPartialFlag.js';
import { ContactTag1730824832555 } from './migrations/1730824832555-ContactTag.js';
import { RemoveContactProfileTag1730983012356 } from './migrations/1730983012356-RemoveContactProfileTag.js';
import { FixContactTagAssignment1731076113379 } from './migrations/1731076113379-fixContactTagAssignment.js';
import { MigrateSegmentTagRules1731670066414 } from './migrations/1731670066414-MigrateSegmentTagRules.js';
import { AddCalloutReviewer1732098141720 } from './migrations/1732098141720-AddCalloutReviewer.js';
import { AddNLOptInRemovePwCallouts1743001845903 } from './migrations/1743001845903-AddNLOptInRemovePwCallouts.js';
import { AddCalloutResponseNLSchema1744119761125 } from './migrations/1744119761125-AddCalloutResponseNLSchema.js';
import { AddNLToCaloutResponse1744644045273 } from './migrations/1744644045273-AddNLToCaloutResponse.js';
import { DeleteUploadFlow1746701227606 } from './migrations/1746701227606-DeleteUploadFlow.js';
import { AddPaymentContent1749237082653 } from './migrations/1749237082653-AddPaymentContent.js';
import { AddCalloutVariantId1750260710855 } from './migrations/1750260710855-AddCalloutVariantId.js';
import { AddReviewerCanEdit1752486366243 } from './migrations/1752486366243-AddReviewerCanEdit.js';
import { ResponseLinkText1754653464755 } from './migrations/1754653464755-responseLinkText.js';
import { AddCalloutResponseSegment1755526570609 } from './migrations/1755526570609-AddCalloutResponseSegment.js';
import { AddDefaultCalloutResponseSegments1755526570700 } from './migrations/1755526570700-AddDefaultCalloutResponseSegments.js';
import { UpdateCalloutFormSchemaComponents1756466495968 } from './migrations/1756466495968-UpdateCalloutFormSchemaComponents.js';
import { AddCalloutResponseEmail1760107926234 } from './migrations/1760107926234-AddCalloutResponseEmail.js';
import { AddEmailTemplateId1764325270075 } from './migrations/1764325270075-AddEmailTemplateId.js';
import { AddInvoicePaymentType1769451523913 } from './migrations/1769451523913-AddInvoicePaymentType.js';
import { MigrateTaxOptions1769782234884 } from './migrations/1769782234884-MigrateTaxOptions.js';
import { AddJoinFormContact1770283990739 } from './migrations/1770283990739-AddJoinFormContact.js';
import { JoinFlowContactManyToOne1770303560600 } from './migrations/1770303560600-JoinFlowContactManyToOne.js';
import { MigrateStripeOptions1771840338000 } from './migrations/1771840338000-MigrateStripeOptions.js';
import { RenameJoinEntities1772449442905 } from './migrations/1772449442905-RenameJoinEntities.js';
import { AddSignupFlow1772461466485 } from './migrations/1772461466485-AddSignupFlow.js';
import { UpdatePaymentFlow1772473765054 } from './migrations/1772473765054-UpdatePaymentFlow.js';
import { AddJoinFlowProcessingFlag1772636569908 } from './migrations/1772636569908-AddJoinFlowProcessingFlag.js';
import { UniqueEmailId1773823606137 } from './migrations/1773823606137-UniqueEmailId.js';
import { ExtendMemberRoleExpiry1774540406786 } from './migrations/1774540406786-ExtendMemberRoleExpiry.js';
import { AddMailchimpNLGroups1776955640900 } from './migrations/1776955640900-AddMailchimpNLGroups.js';

export const migrations = [
  SessionTable1616677358190,
  InitDatabase1616679012431,
  AddSegmentOrder1616693016456,
  AddDefaultSegments1616694307645,
  AddSegmentNewsletterListId1618488866877,
  RenameListIdToTag1619099359790,
  OptionalMemberCodes1619113429486,
  DeliveryOptInDefault1620225385309,
  AddNewsletterFieldsToProfile1620381066389,
  AddEmailAndPasswordToJoinFlow1621513644609,
  AddPollResponsePassword1624370860614,
  RenameJoinFlowAmountToMonthlyAmount1624469115041,
  ConvertMonthlyAmountToReal1624469629114,
  AddMemberActivatedField1626344080098,
  AddButtonText1632397910432,
  UseEmailInSegmentOngoingEmail1632931118456,
  AddContent1632994213635,
  AddExcerptAndImageToPoll1634125137636,
  AddResetPasswordFlow1634737662792,
  RemoveRestartFlow1635350051303,
  FormatEmailBody1638448727069,
  RemovePasswordResetCode1638975520912,
  JoinFlowRedirectFlowOptional1639075139123,
  MigrateJoinFlowOptions1639655491472,
  ChangeDefaultNewsletterStatus1639665377317,
  AddAllowMultiplePollResponses1639760915487,
  UnifyItemStatuses1646649540217,
  MakeImageFieldNonNullable1646649663368,
  ConvertAllPollsToBuilderTemplate1648725496337,
  UpdateDefaultSegments1650535261889,
  AddEmptyGeneralContent1650535712817,
  AddDefaultContent1650537835623,
  AddPaymentMethodToJoinForm1650900384747,
  NonNullRedirectFlowId1650904701374,
  AddContactsContent1651058503997,
  RenameRedirectFlowToPaymentFlow1651068668585,
  AddUrlsToJoinFlow1652115873327,
  AddShareFieldsToPoll1652276361695,
  RenameGoCardlessToAutomatic1652285362376,
  AddPaymentData1652966714320,
  AddPayment1653488390953,
  MigratePaymentTables1653495059460,
  RemoveNextContributionAmount1655199299904,
  MigrateManualPaymentData1655393209607,
  OptionalFromEmailFields1656001166095,
  AddOptionalFirstAndLastNameToJoinFlow1656347461817,
  ConvertPaymentStatuses1656935238800,
  OptionalButtonText1659968561064,
  AddShareContent1660235362253,
  AddEmailContent1660562732237,
  FixSegmentRuleGroups1665070450970,
  UpdateRuleValues1667846310950,
  RenameModels1670242308699,
  RenameModelReferences1670257047310,
  RenameAutoGeneratedKeyIds1670258044685,
  RenamePollModelReferences1670260399264,
  AddCalloutResponseBucket1676460782435,
  FixContactProfileKeys1676623400914,
  AddCalloutTag1676654870090,
  AddCalloutResponseTag1676655715419,
  AddCalloutResponseNumber1678287340165,
  MakeBucketNonNullable1678358909981,
  AddCalloutResponseAssignee1678884024926,
  AddCalloutResponseCommentTable1678888737358,
  AddUpdatedAtToCalloutResponseComment1678898590335,
  ModifyCommentForeignKeyRestraints1678974773924,
  RemoveDefaultFormSchema1679064034052,
  AddApiKeyModel1685528456765,
  UpdateApiKeyModel1686233596892,
  ApiKeyDescriptioNotNull1686233847551,
  AddCalloutMapSchema1690389664790,
  AddUploadFlow1691577150283,
  AddUploadUsedCol1691597308499,
  AddCalloutResponseViewSchema1692289610630,
  PaymentDataCancelledAt1694009247783,
  RenamePollOptions1696506058706,
  UpdateGCNextAmount1696600862719,
  NewCalloutSlideSchema1697020619835,
  DeleteOld2FA1698338165267,
  AddContactMfa1698418165066,
  AddApiKeyExpiryDate1698938717666,
  RenameResetPasswordFlowToResetSecurityFlow1700131647453,
  UpdateIndexes1701968585255,
  UpdateCalloutTag1703247945472,
  ConvertChargeDateToDate1706113195469,
  AddCalloutId1708615794655,
  AddCalloutVariant1708685548000,
  ChangeVariantLocaleToName1708688873027,
  AddCalloutCaptchaField1709217978680,
  AddCalloutVariantFormTexts1709297783048,
  AddExtraJoinFormFields1712158796671,
  RemoveJoinFormBillingAddress1712163090314,
  RenamePaymentDataToContactContribution1713373413805,
  FlattenContributionData1713434533086,
  CalloutChannels1715184967411,
  ImproveContactFieldTypes1715355140741,
  RemoveResponseIsPartialFlag1729522899474,
  ContactTag1730824832555,
  RemoveContactProfileTag1730983012356,
  FixContactTagAssignment1731076113379,
  MigrateSegmentTagRules1731670066414,
  AddCalloutReviewer1732098141720,
  AddNLOptInRemovePwCallouts1743001845903,
  AddCalloutResponseNLSchema1744119761125,
  AddNLToCaloutResponse1744644045273,
  DeleteUploadFlow1746701227606,
  AddPaymentContent1749237082653,
  AddCalloutVariantId1750260710855,
  AddReviewerCanEdit1752486366243,
  ResponseLinkText1754653464755,
  AddCalloutResponseSegment1755526570609,
  AddDefaultCalloutResponseSegments1755526570700,
  UpdateCalloutFormSchemaComponents1756466495968,
  AddCalloutResponseEmail1760107926234,
  AddEmailTemplateId1764325270075,
  AddInvoicePaymentType1769451523913,
  MigrateTaxOptions1769782234884,
  AddJoinFormContact1770283990739,
  JoinFlowContactManyToOne1770303560600,
  MigrateStripeOptions1771840338000,
  RenameJoinEntities1772449442905,
  AddSignupFlow1772461466485,
  UpdatePaymentFlow1772473765054,
  AddJoinFlowProcessingFlag1772636569908,
  UniqueEmailId1773823606137,
  ExtendMemberRoleExpiry1774540406786,
  AddMailchimpNLGroups1776955640900,
];
