import { readFile, readdir, writeFile } from 'node:fs/promises';
import { basename, relative, resolve } from 'node:path';

import type { GenerateClassIndexArgs } from '../types/index.ts';

const HEADER =
  '// Auto-generated by `@beabee/dev-cli generate-class-index`. Do not edit by hand.\n';

/**
 * Generate an index file with explicit imports of every class in a
 * directory plus an aggregated array export. Replaces glob patterns
 * (e.g. `__dirname + '/*.js'`) that break under ESM. Commonly used
 * for TypeORM entities/migrations and any other "list of classes
 * collected from a directory" use case.
 */
export const generateClassIndex = async (
  argv: GenerateClassIndexArgs
): Promise<void> => {
  const { srcDir, outFile, exportName, classNameStrategy, baseDir, check } =
    argv;

  const srcAbs = resolve(baseDir, srcDir);
  const outAbs = resolve(baseDir, outFile);
  const importPrefix =
    './' + relative(resolve(outAbs, '..'), srcAbs).replace(/\\/g, '/');

  const files = (await readdir(srcAbs, { withFileTypes: true }))
    .filter(
      (f) =>
        f.isFile() &&
        f.name.endsWith('.ts') &&
        !f.name.endsWith('.d.ts') &&
        !f.name.endsWith('.test.ts') &&
        f.name !== 'index.ts'
    )
    .map((f) => f.name)
    .sort((a, b) => a.localeCompare(b));

  const entries: Array<{ className: string; importPath: string }> = [];

  for (const fileName of files) {
    const moduleName = basename(fileName, '.ts');
    const importPath = `${importPrefix}/${moduleName}.js`;

    let className: string;
    if (classNameStrategy === 'filename') {
      className = moduleName;
    } else {
      const source = await readFile(resolve(srcAbs, fileName), 'utf-8');
      const match = source.match(/^export class (\w+)/m);
      if (!match) {
        throw new Error(
          `generate-class-index: could not find an "export class" in ${fileName}`
        );
      }
      className = match[1];
    }

    entries.push({ className, importPath });
  }

  const importLines = entries
    .map((e) => `import { ${e.className} } from '${e.importPath}';`)
    .join('\n');

  const arrayLines = entries.map((e) => `  ${e.className},`).join('\n');

  const content = `${HEADER}${importLines}\n\nexport const ${exportName} = [\n${arrayLines}\n];\n`;

  if (check) {
    let existing: string | null = null;
    try {
      existing = await readFile(outAbs, 'utf-8');
    } catch {
      // file missing → drift
    }
    if (existing !== content) {
      console.error(
        `generate-class-index --check: ${outFile} is out of date.\n` +
          `Run \`yarn generate:class-index\` to refresh it.`
      );
      process.exitCode = 1;
      return;
    }
    console.log(`generate-class-index --check: ${outFile} is up to date.`);
    return;
  }

  await writeFile(outAbs, content, 'utf-8');
  console.log(
    `generate-class-index: wrote ${entries.length} entries to ${outFile}`
  );
};
