name: Backend Check

on: [pull_request, workflow_call]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: yarn check:prettier
        working-directory: ./apps/backend

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: yarn build:types
      - run: yarn check:tsc
        working-directory: ./apps/backend

  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: yarn check:dependencies
        working-directory: ./apps/backend
