name: Backend Deploy

on:
  push:
    branches: ["main", "dev"]

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.setvars.outputs.tag }}
      stack: ${{ steps.setvars.outputs.stack }}
    steps:
      - id: setvars
        run: |
          case "${{ github.ref }}" in
            refs/heads/main)
              echo "tag=latest" >> $GITHUB_OUTPUT
              echo "stack=beabee-demo" >> $GITHUB_OUTPUT
              ;;
            refs/heads/dev)
              echo "tag=dev" >> $GITHUB_OUTPUT
              echo "stack=beabee-dev" >> $GITHUB_OUTPUT
              ;;
          esac

  check:
    name: Check
    uses: ./.github/workflows/backend-check.yml

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: cp .env.example .env
        working-directory: ./apps/backend
      - run: yarn test
        working-directory: ./apps/backend

  build-push:
    name: Build and push
    uses: ./.github/workflows/backend-build-push.yml
    needs: [init, check, test]
    secrets: inherit

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [init, push]
  #   steps:
  # TODO: Switch to https://github.com/luminos-company/portami
  #     - uses: jonasschatz/portami@main
  #       with:
  #         endpoint: "https://port.hive.beabee.io"
  #         access_token: ${{ secrets.PORTAINER_ACCESSTOKEN }}
  #         stack_name: ${{ needs.init.outputs.stack }}
  #         prune: true
  #         pull: true
