name: Backend Deploy

on:
  push:
    branches: ["main", "dev"]

jobs:
  check:
    uses: ./.github/workflows/backend-check.yml

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: yarn presetup
      - run: yarn test
        working-directory: ./apps/backend

  push:
    runs-on: ubuntu-latest
    needs: [check, test]
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Init
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=false
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=dev,enable=${{ github.ref == 'refs/heads/dev' }}
            type=raw,value=release,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build legacy app
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/backend/Dockerfile
          push: true
          build-args: |
            REVISION=${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels}}
          target: legacy_app
          tags: ${{ secrets.DOCKER_ORGANISATION }}/beabee-legacy-app:${{ steps.meta.outputs.tags }}

      - name: Build API app
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/backend/Dockerfile
          push: true
          build-args: |
            REVISION=${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels}}
          target: api_app
          tags: ${{ secrets.DOCKER_ORGANISATION }}/beabee-api-app:${{ steps.meta.outputs.tags }}

      - name: Build webhook app
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/backend/Dockerfile
          push: true
          build-args: |
            REVISION=${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels}}
          target: webhook_app
          tags: ${{ secrets.DOCKER_ORGANISATION }}/beabee-webhook-app:${{ steps.meta.outputs.tags }}

      - name: Build cron app
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/backend/Dockerfile
          push: true
          build-args: |
            REVISION=${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels}}
          target: cron_app
          tags: ${{ secrets.DOCKER_ORGANISATION }}/beabee-cron-app:${{ steps.meta.outputs.tags }}
