name: Backend Deploy

on:
  push:
    branches: ["main", "dev"]

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.setvars.outputs.tag }}
      stack: ${{ steps.setvars.outputs.stack }}
    steps:
      - id: setvars
        run: |
          case "${{ github.ref }}" in
            refs/heads/main)
              echo "tag=latest" >> $GITHUB_OUTPUT
              echo "stack=beabee-demo" >> $GITHUB_OUTPUT
              ;;
            refs/heads/dev)
              echo "tag=dev" >> $GITHUB_OUTPUT
              echo "stack=beabee-dev" >> $GITHUB_OUTPUT
              ;;
          esac

  check:
    uses: ./.github/workflows/backend-check.yml

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: yarn presetup
      - run: yarn test
        working-directory: ./apps/backend

  push:
    runs-on: ubuntu-latest
    needs: [init, check, test]
    steps:
      - uses: actions/checkout@v4
      - id: getrev
        run: |
          echo "revision=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/backend/Dockerfile
          push: true
          target: app
          build-args: |
            REVISION=${{ steps.getrev.outputs.revision }}
          tags: ${{ secrets.DOCKER_ORGANISATION }}/beabee:${{ needs.init.outputs.tag }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/backend/Dockerfile
          push: true
          target: router
          tags: ${{ secrets.DOCKER_ORGANISATION }}/router:${{ needs.init.outputs.tag }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [init, push]
  #   steps:
  # TODO: Switch to https://github.com/luminos-company/portami
  #     - uses: jonasschatz/portami@main
  #       with:
  #         endpoint: "https://port.hive.beabee.io"
  #         access_token: ${{ secrets.PORTAINER_ACCESSTOKEN }}
  #         stack_name: ${{ needs.init.outputs.stack }}
  #         prune: true
  #         pull: true
