name: Browser tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  run-browser-tests:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello world"
