name: Browser tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  run-browser-tests:
    if: >
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request_review' && github.event.review.state == 'approved')
    runs-on: ubuntu-latest
    env:
      COMPOSE_PROJECT_NAME: beabee-browser-tests-${{ github.run_id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          stripe_public_key: ${{ secrets.BEABEE_STRIPE_PUBLICKEY }}
          stripe_secret_key: ${{ secrets.BEABEE_STRIPE_SECRETKEY }}

      - uses: ./.github/actions/test-setup
        with:
          stripe_webhook_secret: ${{ secrets.BEABEE_STRIPE_WEBHOOKSECRET }}
          stripe_membership_product_id: ${{ secrets.BEABEE_STRIPE_MEMBERSHIPPRODUCTID }}

      - name: Playwright setup
        run: yarn workspace @beabee/browser-tests playwright install firefox --with-deps

      - name: Run Playwright tests
        id: playwright_tests
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:${{ env.ROUTER_PORT }}
        run: yarn workspace @beabee/browser-tests test

      - name: Export database
        if: failure()
        run: docker compose -f docker-compose.test.yml exec -T api_app yarn backend-cli database export --anonymize=none >> post-playwright-dump.sql

      - name: Upload database dump
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: database
          path: ./post-playwright-dump.sql

      - name: Export Docker logs
        if: failure()
        run: docker compose -f docker-compose.test.yml logs | tee docker-compose.log

      - name: Upload Docker logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose-logs
          path: ./docker-compose.log

      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: ./apps/browser-tests/test-results
