name: Check Workspace

on: [pull_request, workflow_call]

jobs:
  check:
    name: Build and check the complete workspace
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: yarn check
  test:
    name: Build and test the complete workspace
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: yarn test
