name: Check

on: [pull_request, workflow_call]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: yarn check
      - run: yarn build
      - run: yarn test
