name: Common Check

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

permissions:
  contents: read

jobs:
  linux:
    strategy:
      matrix:
        node-version: [22.x]
        deno-version: [v2.0.3]
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Run yarn workspaces focus
        run: yarn workspaces focus
        working-directory: ./packages/common

      - name: Run Deno linter
        run: deno task lint
        working-directory: ./packages/common

      - name: Run Deno check
        run: deno task check
        working-directory: ./packages/common

      - name: Test the types
        run: yarn test:types
        working-directory: ./packages/common

      - name: Run Deno tests
        run: deno task test:deno
        working-directory: ./packages/common

      - name: Run Node builds
        run: yarn build
        working-directory: ./packages/common

      - name: Run Node.js tests
        run: yarn test:node
        working-directory: ./packages/common
