name: Get database report

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  generate-db-report:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event.review.state == 'approved'

    steps:
      - name: Say hello
        run: echo "Hello world"
