name: Get database report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-db-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 24.x
      - name: Install dependencies, compile and bootstrap
        run: yarn install && yarn build && yarn bootstrap
        shell: bash

      - name: Load environment variables
        run: cat .env .env.test | sed -e 's/[[:space:]]*#.*$//' -e '/^[[:space:]]*$/d' >> $GITHUB_ENV

      - name: Bring db and migration up
        run: docker compose -f docker-compose.test.yml -p beabee-db-schema up -d --build db migration

      - name: Generate schemaspy report
        run: |
          mkdir -p db-report

          docker run --rm --user root \
            --network beabee-db-schema_default \
            -v "$(pwd)/db-report:/output" \
            schemaspy/schemaspy:latest \
            -t pgsql \
            -host db \
            -port 5432 \
            -db membership_system \
            -u membership_system \
            -p membership_system \
            -s public -noInfo

      - name: Upload SchemaSpy report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: database-report
          path: ./db-report
