name: Backend build and push

on:
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.build-push.outputs.version }}

jobs:
  build-push:
    name: Run
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.meta.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=false
          images: ${{ secrets.DOCKER_ORGANISATION }}/deno-node
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=dev,enable=${{ github.ref == 'refs/heads/dev' }}
            type=raw,value=release,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/deno-node/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            REVISION=${{ github.sha }}
            VERSION=${{ steps.meta.outputs.version }}
