name: Frontend Deploy

on:
  push:
    branches: ["main", "dev"]

jobs:
  check:
    name: Check
    uses: ./.github/workflows/frontend-check.yml

  build-push:
    name: Build and push
    uses: ./.github/workflows/frontend-build-push.yml
    needs: [check]
    secrets: inherit
