name: Frontend Deploy

on:
  push:
    branches: ["main", "dev"]

jobs:
  init:
    name: Initialise
    runs-on: ubuntu-latest

    outputs:
      stack: ${{ steps.getstage.outputs.stack }}

    steps:
      - id: getstage
        run: |
          case "${{ github.ref }}" in
            refs/heads/main)
              echo "stack=beabee-demo" >> $GITHUB_OUTPUT
              ;;
            refs/heads/dev)
              echo "stack=beabee-dev" >> $GITHUB_OUTPUT
              ;;
          esac

  check:
    name: Check
    uses: ./.github/workflows/check.yml

  node-deno-build-push:
    name: Build and push
    uses: ./.github/workflows/deno-node-build-push.yml
    needs: [init]
    secrets: inherit

  frontend-build-push:
    name: Build and push
    uses: ./.github/workflows/frontend-build-push.yml
    needs: [init, check, node-deno-build-push]
    secrets: inherit

  backend-build-push:
    name: Build and push
    uses: ./.github/workflows/backend-build-push.yml
    needs: [init, check, node-deno-build-push]
    secrets: inherit

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [init, build-push]
  #   steps:
  # TODO: Switch to https://github.com/luminos-company/portami
  #     - uses: jonasschatz/portami@main
  #       with:
  #         endpoint: "https://port.hive.beabee.io"
  #         access_token: ${{ secrets.PORTAINER_ACCESSTOKEN }}
  #         stack_name: ${{ needs.init.outputs.stack }}
  #         prune: true
  #         pull: true
