name: Frontend Release

on:
  push:
    tags:
      - "v*"

jobs:
  check:
    name: Frontend check
    uses: ./.github/workflows/frontend-check.yml

  build-push:
    name: Frontend build and push
    uses: ./.github/workflows/frontend-build-push.yml
    needs: [check]
    secrets: inherit

  release:
    name: Release frontend
    runs-on: ubuntu-latest
    needs: [build-push]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: beabee-communityrm/hive-deploy-stack
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: |
          git config --global user.name "Deploy bot"
          git config --global user.email "<>"

          echo -n ${{ needs.build-push.outputs.version }} > FRONTEND_VERSION
          ./update.sh

          git add FRONTEND_VERSION docker-compose.yml
          if ! git diff --quiet --cached; then
            git commit -m "Deploy frontend ${{ needs.build-push.outputs.version }}"
            git push
          fi
