name: Router Deploy

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.setvars.outputs.tag }}
    steps:
      - id: setvars
        run: |
          if [[ "${{ github.event.inputs.stage }}" == "dev" || "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "tag=dev" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

  push:
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - uses: actions/checkout@v4
      - id: getrev
        run: |
          echo "revision=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/router/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_ORGANISATION }}/beabee-router:${{ needs.init.outputs.tag }}
