name: Test on Approval

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request_review:
    types: [submitted]

jobs:
  test:
    # Run for workflow_dispatch, push to main, or approved pull request reviews
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          stripe_public_key: ${{ secrets.BEABEE_STRIPE_PUBLICKEY }}
          stripe_secret_key: ${{ secrets.BEABEE_STRIPE_SECRETKEY }}

        # Deprecated:
        # Currently uses the MigrateStripeOptions migration to set the
        # stripe-webhook-secret option, this should be changed when the E2E
        # tests are updated
      - name: Set Stripe environment variables
        shell: bash
        run: |
          sed -i "s|BEABEE_STRIPE_WEBHOOKSECRET=|BEABEE_STRIPE_WEBHOOKSECRET=${{ secrets.BEABEE_STRIPE_WEBHOOKSECRET }}|" .env.test
          sed -i "s|BEABEE_STRIPE_MEMBERSHIPPRODUCTID=|BEABEE_STRIPE_MEMBERSHIPPRODUCTID=${{ secrets.BEABEE_STRIPE_MEMBERSHIPPRODUCTID }}|" .env.test

      - name: Run tests
        run: yarn test
